feat: add infra id range check
eve-autonomy/cargo_loading_service pull request #10
Opened 2023-03-09 12:22 UTC by v-sugahara7993-esol

## Description

This PR adds a range check for infrastructure IDs passed to the service.
If an invalid ID is passed to the service, the service response will return failure.

## Related links

* Jira ticket
    * [Ticket (COMPANY INTERNAL LINK)]

[Ticket (COMPANY INTERNAL LINK)]: https://tier4.atlassian.net/browse/T4PB-26900

## Tests performed

The tests described below were conducted.

* Verified that the package can be built without Error/Warning by `colcon`.
* Verified what was described in the Test Case.

<details><summary>Test Case</summary>
<p>

| No |Description|
|----|---|
| 1 |If an invalid value (0 or 255) is passed in the service request, do not send a command message. The service response shall return failure.|

</p>
</details>

## Notes for reviewers

None.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-03-10 00:32 UTC, sfukuta requested changes

2023-03-10 00:32 UTC, sfukuta commented on src/cargo_loading_service.cpp
> +      infra_id_ <= static_cast<std::underlying_type<InfraIdLimit>::type>(InfraIdLimit::MAX)) {
以下でも、動作すると思いますが、static_castをしないと動作に問題がありますか？
```suggestion
  if (infra_id_ >= InfraIdLimit::MIN && infra_id_ <= InfraIdLimit::MAX) {
```

2023-03-10 00:50 UTC, v-sugahara7993-esol commented on src/cargo_loading_service.cpp
> +      infra_id_ <= static_cast<std::underlying_type<InfraIdLimit>::type>(InfraIdLimit::MAX)) {
static_castをしているのはビルドエラー/ワーニング対策です。
厳密に型チェックが入るため、enumのほうでuint8_tをベースに指定していても、型不一致扱いとなります。ご指摘のコードでビルドするとビルドエラーが発生します。

2023-03-10 01:09 UTC, sfukuta commented on src/cargo_loading_service.cpp
> +      infra_id_ <= static_cast<std::underlying_type<InfraIdLimit>::type>(InfraIdLimit::MAX)) {
修正不要で了解です。

2023-03-10 01:10 UTC, sfukuta approved these changes

2023-03-10 01:28 UTC, m-iwashita-esol approved these changes

2023-03-10 03:03 UTC, sfukuta requested changes

2023-03-10 03:03 UTC, sfukuta commented on src/cargo_loading_service.cpp
> +      infra_id_ <= static_cast<std::underlying_type<InfraIdLimit>::type>(InfraIdLimit::MAX)) {
"static_cast<uint8_t>"に変更をお願いしたいです。

2023-03-10 03:25 UTC, yn-mrse requested changes

2023-03-10 03:25 UTC, yn-mrse commented on src/cargo_loading_service.cpp
>    service_result_ = ExecuteInParkingTask::Response::SUCCESS;
```suggestion
  if (request->id < static_cast<uint8_t>(InfraIdLimit::MIN) ||
      request->id > static_cast<uint8_t>(InfraIdLimit::MAX)) {
      RCLCPP_WARN(this->get_logger(), "Invalid ID = %d", request->id);
      response->state = ExecuteInParkingTask::Response::FAIL;
      return;
  }
  infra_id_ = request->id;
  service_result_ = ExecuteInParkingTask::Response::SUCCESS;
```
- service call時のINVALID IDは、サービスがまだ開始されない段階であるため、service_resultの失敗による設備への終了指示（0b00）を送る必要がないです。responseのみFailで返してください。
- ソースコードの見通しを良くするため、early returnを心がけてください。
- INVALID ID時はサービス開始すらしていないのでinfra_id_の変更も不要です。

2023-03-10 03:25 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +    }
```suggestion
  // 設備連携要求開始
  if (timer_->is_canceled()) {
      timer_->reset();
    RCLCPP_DEBUG(this->get_logger(), "Timer restart");
  }
```

2023-03-10 03:25 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +    service_result_ = ExecuteInParkingTask::Response::FAIL;
```suggestion
  // キャンセルになるまで設備連携要求を投げ続ける
  while (!timer_->is_canceled()) {
    rclcpp::sleep_for(rclcpp::Rate(command_pub_hz_).period());
    RCLCPP_INFO_THROTTLE(
      this->get_logger(), *this->get_clock(), 1000 /* ms */, "request is running");
```

2023-03-11 11:14 UTC, yn-mrse requested changes

2023-03-11 11:14 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +      timer_->reset();
```suggestion
    timer_->reset();
```

2023-03-11 11:14 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +  }
```suggestion
  if (request->id < static_cast<uint8_t>(InfraIdLimit::MIN) ||
      request->id > static_cast<uint8_t>(InfraIdLimit::MAX)) {
      RCLCPP_WARN(this->get_logger(), "Invalid ID = %d", request->id);
      response->state = ExecuteInParkingTask::Response::FAIL;
      return;
  }
  // 設備ID取得
```

2023-03-11 11:19 UTC, yn-mrse approved these changes

2023-03-11 11:19 UTC, merged