fix: replace the magic number with a defined constant
eve-autonomy/cargo_loading_service pull request #11
Opened 2023-03-09 12:35 UTC by v-sugahara7993-esol

## Description

In this PR, the definition of constants is added, and where magic numbers were used, they are replaced with the added constants.

## Related links

* Jira ticket
    * [Ticket (COMPANY INTERNAL LINK)]

[Ticket (COMPANY INTERNAL LINK)]: https://tier4.atlassian.net/browse/T4PB-26930

## Tests performed

The tests described below were conducted.

* Verified that the package can be built without Error/Warning by `colcon`.
* Verified what was described in the Test Case.

<details><summary>Test Case</summary>
<p>

| No |Description|
|----|---|
| 1 |When completion is notified in the infrastructure state, the completion process should be performed. (regression testing)|
| 2 |When a value other than completion is notified in the infrastructure state, the completion process should not be performed. (regression test)|

</p>
</details>

## Notes for reviewers

None.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-03-10 00:28 UTC, sfukuta approved these changes

2023-03-10 04:06 UTC, yn-mrse requested changes

2023-03-10 04:06 UTC, yn-mrse commented on include/cargo_loading_service/cargo_loading_service.hpp
> +  static constexpr uint8_t APPROVAL_VALUE = 0b01;
```suggestion
  enum class ReceiveState : uint8_t { APPROVAL = 0b01 };
```

2023-03-10 04:06 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +    infra_approval_ = (e.state == APPROVAL_VALUE);
```suggestion
    infra_approval_ = (e.state == static_cast<uint8_t>(ReceiveState::APPROVAL));
```

2023-03-10 04:06 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +    if (e.state != APPROVAL_VALUE) {
```suggestion
    if (e.state != static_cast<uint8_t>(ReceiveState::APPROVAL)) {
```

2023-03-10 04:06 UTC, yn-mrse commented on src/cargo_loading_service.cpp
>      // 成功した場合、0b01が返ってくる
```suggestion
    // 成功した場合、APPROVALが返ってくる
```

2023-03-10 04:06 UTC, yn-mrse commented on src/cargo_loading_service.cpp
>      // 0b01じゃない場合、エラー出力
```suggestion
    // APPROVALじゃない場合、エラー出力
```

2023-03-10 08:44 UTC, m-iwashita-esol approved these changes

2023-03-11 11:21 UTC, yn-mrse approved these changes

2023-03-11 11:21 UTC, merged