feat: implementation of command send process
eve-autonomy/cargo_loading_service pull request #2
Opened 2023-02-21 07:18 UTC by v-sugahara7993-esol

## Description

This PR adds a process for nodes with services that require sending commands to facilities.

See [NODE-GRAPH(COMPANY INTERNAL LINK)](https://tier4.atlassian.net/wiki/spaces/AIP/pages/2674065672/) for messages between nodes. See [Cargo Loading Service Module(COMPANY INTERNAL LINK)](https://tier4.atlassian.net/wiki/spaces/AIP/pages/2681569626/EVPJ-107) for the design of modules containing nodes.

Also, the following remarks remained in the previous pull request have been corrected.
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107921356
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107922027
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107924613
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107925149
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107925850
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107938391
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107943175
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107944728
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107945292
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107951148
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107952195
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107953611
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107954015
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107954815
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107955597
* https://github.com/eve-autonomy/cargo_loading_service/pull/1#discussion_r1107959533

TODO: The part where state and status are different in naming will be discussed and corrected after the 2nd make's PR has run its course.

## Related links

* Message Design
   * [NODE-GRAPH(COMPANY INTERNAL LINK)](https://tier4.atlassian.net/wiki/spaces/AIP/pages/2674065672/)
* Module Design
   * [Cargo Loading Service Module(COMPANY INTERNAL LINK)](https://tier4.atlassian.net/wiki/spaces/AIP/pages/2681569626/EVPJ-107)
* Jira ticket
   * [Ticket(COMPANY INTERNAL LINK)](https://tier4.atlassian.net/browse/T4PB-25941)

## Tests performed

The tests described below were conducted.

* Verified that the package can be built without Error/Warning by `colcon`.
* We started the node and waited for more than 1 minute to confirm that it did not CoreDump.
* Verified the input/output values of the nodes in the description of [Cargo Loading Service Module(COMPANY INTERNAL LINK)](https://tier4.atlassian.net/wiki/spaces/AIP/pages/2681569626/EVPJ-107).
   * Confirmation details are listed in Cargo Loading Service Checkpoint at the bottom.
   * The input/output values to be checked are listed in Cargo Loading Service Test Target at the bottom.
   * Details of the test can be found in ". /test/cargo_loading_service_test.md" for details.
* Verified that the node can communicate for the description of [NODE-GRAPH(COMPANY INTERNAL LINK)](https://tier4.atlassian.net/wiki/spaces/AIP/pages/2674065672/).
   * The details of the checks, the target to be checked, and the test are the same as for the check on the [Cargo Loading Service Module(COMPANY INTERNAL LINK)](https://tier4.atlassian.net/wiki/spaces/AIP/pages/2681569626/EVPJ-107) one above.
      * See Cargo Loading Service Checkpoint and Cargo Loading Service Test Target and 
       ". /test/cargo_loading_service_test.md".
* We have confirmed the startup of the node using the launch file.

<details><summary>Cargo Loading Service Checkpoint</summary>
<p>

|Check Point No.|Description|
|---|---|
|1|The service `/parking/cargo_loading` returns success or failure as the response value.|
|2|Service behavior changes depending on the value of `aw_state` received at `/in_parking/state`.|
|3|Service behavior changes depending on the value of `approval` received in `/infrastructure_status`.|
|4|Service behavior changes depending on the value of `id` received in `/infrastructure_status`.|

</p>
</details>

<details><summary>Node Communication Test Target</summary>
<p>

|Test Target No.|Test Target|Check Point No.|
|---|---|---|
|1 | Return SUCCESS(=1)                               |1|
|2 | Return FAIL(=2)                                  |1|
|3 | aw_state is NONE(=0)                             |2|
|4 | aw_state is AW_EMERGENCY(=1)                     |2|
|5 | aw_state is AW_OUT_OF_PARKING(=2)                |2|
|6 | aw_state is AW_ARRIVED_PARKING(=3)               |2|
|7 | aw_state is AW_INVALID_DEPARTURE_INSTRUCTION(=4) |2|
|8 | aw_state is AW_WAIT_DEPARTURE_INSTRUCTION(=5)    |2|
|9 | aw_state is AW_UNAVAILABLE(=6)                   |2|
|10| approval is true                                 |3|
|11| approval is false                                |3|
|12| Match with ID requested by service               |4|
|13| Mismatch with ID requested by service            |4|

</p>
</details>

## Notes for reviewers

The following outstanding items are included. Additional PR will be added before this feature is released.

* The function that a node should have.
* Description of README.md.
* Correction of remarks by Formatter and Linter.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-02-21 07:35 UTC, h-ohta commented on include/cargo_loading_service/cargo_loading_service.hpp
> +  static constexpr uint8_t CMD_STATE_ERROR = 0b10;
enum classで実装したほうが良さそう？

2023-02-21 07:37 UTC, h-ohta commented on src/cargo_loading_service.cpp
> +  aw_state_(in_parking_msgs::msg::InParkingStatus::NONE)
クラス側で{}初期化

2023-02-21 07:43 UTC, h-ohta commented on src/cargo_loading_service.cpp
> +  timer_ = create_timer(
rclcppのtimerの使っているのはなにか理由があるんでしょうか？

2023-02-21 07:48 UTC, h-ohta commented on src/cargo_loading_service.cpp
> +  timer_ = create_timer(
callback groupによりaw_state_へのアクセスの競合を防ぐため？

2023-02-21 07:50 UTC, h-ohta commented on include/cargo_loading_service/cargo_loading_service.hpp
> +  void onTimer();
不要？

2023-02-21 08:11 UTC, h-ohta commented on src/cargo_loading_service.cpp
> +  timer_ = create_timer(
https://github.com/eve-autonomy/cargo_loading_service/pull/1/files#r1107938391
この指摘と認識

2023-02-21 08:33 UTC, h-ohta commented on include/cargo_loading_service/cargo_loading_service.hpp
> +  std::string facility_id_;
`#include <string>` をつける

2023-02-21 08:34 UTC, h-ohta commented on include/cargo_loading_service/cargo_loading_service.hpp
> +  rclcpp::TimerBase::SharedPtr timer_;
timer変数がサービス内で完結するならメンバ変数は必要ない

2023-02-21 08:40 UTC, h-ohta commented on src/cargo_loading_service.cpp
>    const rclcpp::NodeOptions & options = rclcpp::NodeOptions())
```suggestion
  const rclcpp::NodeOptions & options)
```

2023-02-21 08:41 UTC, h-ohta commented on include/cargo_loading_service/cargo_loading_service.hpp
>    int32_t aw_state_;
```suggestion
  int32_t aw_state_{InParkingStatus::NONE};
```

2023-02-21 08:41 UTC, h-ohta commented on src/cargo_loading_service.cpp
> +  aw_state_(in_parking_msgs::msg::InParkingStatus::NONE)
```suggestion
```

2023-02-21 08:42 UTC, h-ohta commented on src/cargo_loading_service.cpp
> +  facility_id_(""),
```suggestion
```

2023-02-21 08:44 UTC, h-ohta commented on include/cargo_loading_service/cargo_loading_service.hpp
> +  std::string facility_id_;
```suggestion
  std::string facility_id_{""};
```

2023-02-21 08:45 UTC, h-ohta commented on src/cargo_loading_service.cpp
> +  const int32_t finalizing_pub_limit = static_cast<int32_t>(command_pub_hz_ * 2.0);
```suggestion
  const auto finalizing_pub_limit = static_cast<int32_t>(command_pub_hz_ * 2.0);
```

2023-02-21 09:08 UTC, h-ohta commented on include/cargo_loading_service/cargo_loading_service.hpp
> +  std::string facility_id_;
https://github.com/eve-autonomy/cargo_loading_service/pull/2/commits/ef650dc5f7b93a5b13a97bc823463f3723ac3a1f

2023-02-21 09:10 UTC, h-ohta commented on include/cargo_loading_service/cargo_loading_service.hpp
> +  void onTimer();
```suggestion
```

2023-02-21 11:05 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +  timer_ = create_timer(
serviceのみを別callback groupに設定することで、できるだけ排他不備による不具合が起きにくい構造にする狙いです。

2023-02-22 05:07 UTC, h-ohta commented
| No  | テストケース                                                                                                 | 想定挙動                                                                             | 結果 | 
| --- | ------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------ | ---- | 
| 1   | サービスが来ない                                                                                             | command: publishしない                                                               |      | 
| 2   | サービスが来た<br>- aw_stateがNONE                                                                           | command: publishしない<br>サービス: FAILを返す                                       |      | 
| 3   | サービスが来た<br>-  設備連携完了でない<br>- aw_stateがAW_EMERGENCY                                          | command: publish<br>サービス: 何も返さず継続                                         |      | 
| 4   | サービスが来た<br>-  設備連携完了でない<br>- aw_stateがAW_OUT_OF_PARKING<br>- aw_stateがAW_UNAVAILABLE<br>   | command: SEND_ZEROをpublish<br>サービス: FAILを返す                                  |      | 
| 5   | サービスが来た<br>-  設備連携完了でない<br>- aw_stateがAW_ARRIVED_PARKING<br>- aw_stateがAW_STILL_IN_PARKING | command: REQUESTINGをpublish<br>サービス: SUCCCESSを返す<br>サービス: 何も返さず継続 |      | 
| 6   | サービスが来た<br>-  設備連携完了                                                                            | command: SEND_ZEROをn秒間publish<br>サービス: SUCCESSを返す                          |      |

2023-02-22 11:06 UTC, yn-mrse requested changes

2023-02-22 11:06 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +  }
```suggestion
```
排他を考えるとonTimer内に寄せたほうが良いと思います。

2023-02-22 11:06 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +  }
```suggestion
  // キャンセルになるまで設備連携要求を投げ続ける
  while (1) {
    rclcpp::sleep_for(rclcpp::Rate(command_pub_hz_).period());
    RCLCPP_INFO_THROTTLE(
      this->get_logger(), *this->get_clock(), 1000 /* ms */, "request is running");
    std::lock_guard<std::mutex> lock(mutex_);
    if (timer_->is_canceled()) {
      break;
    }
  }
```
- sleepしないとCPU負荷がやばいので追加をお願いします。
- timer_の排他制御に対策が必要と思います。

2023-02-22 11:21 UTC, yn-mrse requested changes
OUT_OF_PARKING等で一瞬だけ0b00を送る仕様を修正したいです。
下記のsuggested change反映で治るかと思います。
（ 関連：https://github.com/eve-autonomy/cargo_loading_service/pull/2#discussion_r1114236118 ）

2023-02-22 11:21 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +    service_result_ = ExecuteInParkingTask::Response::SUCCESS;
```suggestion
    infra_approval_ = false;
```

2023-02-22 11:21 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +  facility_id_ = request->value;
```suggestion
  service_result_ = ExecuteInParkingTask::Response::SUCCESS;
  // 設備ID取得
  facility_id_ = request->value;
```

2023-02-22 11:21 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +  infra_approval_ = false;
```suggestion
```

2023-02-22 11:21 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +        timer_->cancel();
```suggestion
        infra_approval_ = true;
        service_result_ = ExecuteInParkingTask::Response::FAIL;
```

2023-02-22 11:28 UTC, yn-mrse requested changes

2023-02-22 11:28 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +      case InParkingStatus::AW_UNAVAILABLE:
```suggestion
      case InParkingStatus::AW_UNAVAILABLE:
      case InParkingStatus::NONE:
```
https://github.com/eve-autonomy/cargo_loading_service/pull/2#discussion_r1114165828
のスレッドでのNONEの移動先はこちらで良いと思います。
この場合、設備に終了通知0b00を送り即時終了します。

2023-02-22 11:32 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +}
aw_state_の値が一定期間取れないときにaw_state = AW_EMERGENCYの処理（設備にエラー通知）が必要かと思います。
この関数のtimeout監視をして、設備連携中（!infra_approval_のとき）にtimeoutが発生した場合にはErrorに入れるなどのFailsafeが期待されるはずです。

ただし今回は時間もないため制限事項として管理する方針でご提案ください。

2023-02-22 11:34 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +void CargoLoadingService::onInParkingStatus(const InParkingStatus::ConstSharedPtr msg)
aw_state_のcallbackが一定期間呼ばれないときにaw_state = AW_EMERGENCYのときの処理（設備にエラー通知）が必要かと思います。
この関数のtimeout監視をして、設備連携中（!infra_approval_のとき）にtimeoutが発生した場合にはErrorに入れるなどのFailsafeが期待されるはずです。

ただし今回は時間もないため制限事項として管理する方針でご提案ください。

2023-02-22 12:04 UTC, yn-mrse requested changes
https://github.com/eve-autonomy/v2i_interface_msgs/pull/2 を反映した場合の追加修正提案です。

2023-02-22 12:04 UTC, yn-mrse commented on include/cargo_loading_service/cargo_loading_service.hpp
> +  static constexpr char COMMAND_TYPE[] = "eva_beacon_system";
```suggestion
```

2023-02-22 12:04 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +  command.type = COMMAND_TYPE;
```suggestion
```

2023-02-22 12:04 UTC, yn-mrse commented on include/cargo_loading_service/cargo_loading_service.hpp
> +  std::string facility_id_;
```suggestion
  uint8_t infra_id_;
```
facility vs infraで使い分けに意味があまりないと思いますので、主流なinfraのほうに修正します。

2023-02-22 12:04 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +  facility_id_ = "";
```suggestion
  infra_id_ = InfrastructureState::INVALID_ID;
```

2023-02-22 12:04 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +  command.id = facility_id_;
```suggestion
  command.id = infra_id_;
```

2023-02-22 12:04 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +    infra_approval_ = msg->states.at(std::distance(msg->states.begin(), itr)).approval;
```suggestion
    infra_approval_ = (msg->states.at(std::distance(msg->states.begin(), itr)).status == CommandState::ERROR);
```

2023-02-22 12:04 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +  });
```suggestion
  if (infra_id_ == InfrastructureState::INVALID_ID) {
    return;
  }
  const auto itr = std::find_if(msg->states.begin(), msg->states.end(), [this](const auto & e) {
    return e.id == infra_id_;
  });
```

2023-02-22 12:09 UTC, yn-mrse requested changes

2023-02-22 12:09 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +  infra_approval_ = false;
```suggestion
```
https://github.com/eve-autonomy/cargo_loading_service/pull/2#discussion_r1114177150 にあわせて削除のコメントをしていましたが誤って消えたため再度コメントします。

2023-02-22 12:13 UTC, h-ohta commented on src/cargo_loading_service.cpp
> +  }
たしかにそうですね。修正します

2023-02-22 12:16 UTC, h-ohta commented on src/cargo_loading_service.cpp
> +  }
たしかにsleepを入れたほうが良さそう
値を書き換えるわけではなければmutexを入れる必要はないです

2023-02-22 12:33 UTC, h-ohta commented on src/cargo_loading_service.cpp
> +  });
```suggestion
  const auto itr = std::find_if(msg->states.begin(), msg->states.end(), [this](const auto & e) {
    return e.id == finfra_id_;
  });
```
でいいんじゃないでしょうか
INVALID_IDの条件分岐は必要ないと思います

2023-02-24 00:49 UTC, sfukuta submitted a review, later dismissed

2023-02-24 04:09 UTC, sfukuta commented on src/cargo_loading_service.cpp
> +  }
反映済みです

2023-02-24 04:09 UTC, sfukuta commented on src/cargo_loading_service.cpp
> +  }
sleepは、対応済み。mutexは不要となります。

2023-02-24 07:50 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +void CargoLoadingService::onInParkingStatus(const InParkingStatus::ConstSharedPtr msg)
[T4PB-26456(TIER IV INTERNAL LINK)](https://tier4.atlassian.net/browse/T4PB-26456)にて管理とし、このスレッドはCloseします。

2023-02-24 08:21 UTC, yn-mrse requested changes

2023-02-24 08:21 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +  infra_id_ = request->value;
```suggestion
  infra_id_ = request->id;
```

2023-02-24 08:21 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +    infra_approval_ = (msg->states.at(std::distance(msg->states.begin(), itr)).status == CommandState::ERROR);
```suggestion
    infra_approval_ = (msg->states.at(std::distance(msg->states.begin(), itr)).state == static_cast<uint8_t>(CommandState::ERROR));
```

2023-02-24 08:23 UTC, yn-mrse approved these changes

2023-02-24 08:23 UTC, merged