fix: add log output locations and change output level in one location
eve-autonomy/cargo_loading_service pull request #8
Opened 2023-03-09 06:51 UTC by v-sugahara7993-esol

## Description

This PR improves error handling in in_parking_task_manager for auto departure requests.

* Changed the method of log output in Emergency status from `RCLCPP_ERROR()` to `RCLCPP_ERROR_THROTTLE()`.
* Changed log output level from `DEBUG` to `INFO` when cargo loading is finished.
* Added log output after sending cargo loading finish command.

## Related links

* Jira ticket
    * [Ticket (COMPANY INTERNAL LINK)]

[Ticket (COMPANY INTERNAL LINK)]: https://tier4.atlassian.net/browse/T4PB-26318

## Tests performed

The tests described below were conducted.

* Verified that the package can be built without Error/Warning by `colcon`.
* Verified that the changed/added logs are output as described in the Test Case.

<details><summary>Test Case</summary>
<p>

| No |Description|
|----|---|
| 1 |A log showing the status of the status shall be output every second during the status of the EMERGENCY. |
| 2 |Logging should be output at the INFO level before the completion of the process that ends cargo loading.|
| 3 |Logs should be output at the INFO level after the completion of the process that ends cargo loading.|

</p>
</details>

## Notes for reviewers

None.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-03-09 07:10 UTC, sfukuta approved these changes

2023-03-10 01:26 UTC, m-iwashita-esol approved these changes

2023-03-10 03:54 UTC, yn-mrse requested changes
下記２箇所について、正常系の中でユーザが手動発車ボタンを押す・運転するなどの動作を行うことで発生するため、WARNではなくINFOへ変更をお願いします。
- https://github.com/eve-autonomy/cargo_loading_service/pull/8/files#diff-325780a633ee4461ae433a9183126eca02b22f9f210fc72da0392a08a816caf0R129
- https://github.com/eve-autonomy/cargo_loading_service/pull/8/files#diff-325780a633ee4461ae433a9183126eca02b22f9f210fc72da0392a08a816caf0R139

2023-03-10 03:54 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +    RCLCPP_INFO(this->get_logger(), "finished");
```suggestion
    RCLCPP_INFO(this->get_logger(), "complete reporting to infrastructure that the cargo loading process is over.");
```

2023-03-10 03:54 UTC, yn-mrse commented on src/cargo_loading_service.cpp
> +    RCLCPP_INFO(this->get_logger(), "finishing");
```suggestion
    RCLCPP_INFO(this->get_logger(), "try reporting to infrastructure that the cargo loading process is over.");
```

2023-03-10 08:03 UTC, sfukuta approved these changes

2023-03-11 11:10 UTC, yn-mrse approved these changes

2023-03-11 11:11 UTC, merged